name: Pack release

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: npm run init && npm run pack
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: npm run init && npm run pack
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: npm run init && npm run pack
