name: Pack Windows

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Setup venv-oysape
        run: |
          python -m venv venv-oysape
          .\venv-oysape\Scripts\pip install -r requirements.txt

      - name: Pack
        run: |
          .\venv-oysape\Scripts\pyinstaller build-windows.spec
          .\venv-oysape\Scripts\pyinstaller build-windows.spec -- --standalone

      # Compress the executable file into a zip file
      - name: Zip the executable
        run: |
          Compress-Archive -Path dist/Oysape-windows-standalone-AMD64.exe -DestinationPath Oysape-windows-standalone.zip

      # Create a release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v3.9.23'
          release_name: 'Oysape Windows Release v3.9.23'
          draft: false
          prerelease: false

      # Upload the zip file as an release asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Oysape-windows-standalone.zip
          asset_name: Oysape-windows-standalone.zip
          asset_content_type: application/zip
