name: Pack MacOS

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v3.9.23)'
        required: true
        default: 'v3.9.23'

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Setup venv-oysape
        run: |
          python3 -m venv venv-oysape
          ./venv-oysape/bin/pip install -r requirements.txt

      - name: Pack to a standalone executable file
        run: |
          ./venv-oysape/bin/python build-macos.py py2app

      # Compress the executable file into a zip file
      - name: Zip the executable
        run: |
          Compress-Archive -Path dist/Oysape.app -DestinationPath Oysape-mac-universal.zip

      # Create release and upload assets in one step
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          name: MacOS Release ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: Oysape-mac-universal.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
